#PBS -N charges
#PBS -q iw-shared-6
#PBS -o fchk.$PBS_JOBID
#PBS -e fchk.$PBS_JOBID
#PBS -l nodes=1:ppn=2
#PBS -l walltime=20:00

cd $PBS_O_WORKDIR


# here we need to use the conda download and environment for newer psi4
# default PACE installation is too old for DMA

module load anaconda3/latest
source activate p4env

export myscratch=~/scratch/psi4.$PBS_JOBID
export PSI_SCRATCH=$myscratch
mkdir -p $PSI_SCRATCH

export PSIDATADIR=""
export PSIDATADIR=~/.conda/envs/p4env/share/psi4/

./run_charges.sh TFSI_190_24 2


rm -r $PSI_SCRATCH
